### ISSUE TITLE
Allow Custom Logger Preferences to be set

### ISSUE THREAD

**Issue by alexnuijten** [OraOpenSource/Logger#103]
There is functionality to get values from the LOGGER_PREFS table for a given name. Currently there is no supported procedure to set name/value pairs in LOGGER_PREFS.
When creating supporting packages, or plugins, it might be useful to persist preferences.
Distinguish between the "built-in" preferences and custom preferences, so you don't get conflicts in future releases, e.g. prefix custom preferences with CUST_
Only allow the already existing preferences or preferences which are prefixed with CUST_
```sql
procedure set_pref (p_pref_name in varchar2
                   ,p_pref_value in varchar2
                   )
is
begin
   $if $$no_op $then
     null;
   $else
      if substr (p_pref_name, 1, 5) = 'CUST_'
      or p_pref_name in ('GLOBAL_CONTEXT_NAME'
                        ,'INCLUDE_CALL_STACK'
                        ,'INSTALL_SCHEMA'
                        ,'LEVEL'
                        ,'LOGGER_DEBUG'
                        ,'LOGGER_VERSION'
                        ,'PLUGIN_FN_ERROR'
                        ,'PREF_BY_CLIENT_ID_EXPIRE_HOURS'
                        ,'PROTECT_ADMIN_PROCS'
                        ,'PURGE_AFTER_DAYS'
                        ,'PURGE_MIN_LEVEL'
                        )
      then
         merge into logger_prefs p
         using (select upper (p_pref_name) pref_name
                      ,p_pref_value pref_value
                  from dual
                  ) args
         on (p.pref_name = args.pref_name)
         when matched then
           update
              set p.pref_value =  args.pref_value  
         when not matched then
           insert
            (pref_name
            ,pref_value)
         values
             (args.pref_name
             ,args.pref_value
             );
      else
         raise_application_error (-20000, 'Only Predefined Preferences and Custom Preferences that begin with "CUST_" are allowed');
      end if;
   $end
end set_pref;
```

**Comment by martindsouza** [comment]
Overall looks good and what we discussed. A few comments:

- Do you think we need to wrap in the `$if $$no_op $then` code? I could argue on both sides of this case but not sure about it since it's for defining a pref.
- I don't think we should open this up to setting non-custom preferences since there's a bit more logic that goes on for some of these settings (ex: see `logger.set_level`). 
  - In that case what do you think about calling the method `set_cust_pref`?

**Comment by alexnuijten** [comment]
* Very good point, only expose it to set Custom Preferences, so ```sql set_cust_pref ``` sounds good to me.
* Yes, I do think ```sql $if $$no_op $then  ``` should be there. If you opt to have Logger not operational, there is no point in setting Custom Preferences.

**Comment by martindsouza** [comment]
Ok. I'm good with these sets of requirements.

We'll also need to update the `logger_prefs` table to ensure there's a constraint that limits the pref_names to the list above and anything with `CUST_`.

Did you want to work on this issue?

**Comment by martindsouza** [comment]
Thanks for doing this. I accepted the merge. One thing that I think we should change is in `set_cust_pref` to auto delete if the value is null. I'd prefer if we didn't do the delete automatically. I can see an issue if people create null values so that they can always do a `select` statement and not have to worry if their value is present.

What do you think about creating a `del_cust_pref` to perform an explicit delete?

**Comment by alexnuijten** [comment]
I understand what you're saying, but both columns are mandatory (PREF_NAME and PREF_VALUE) so it is not possible to have a custom preference and set the value to NULL - at best it would raise an exception.

Maybe consider increasing the column_size, esp. of PREF_VALUE to allow storage for larger values

**Comment by martindsouza** [comment]
Hmm I forgot about the `NOT NULL` constraint. What do you think about still having the two different methods. `set_cust_pref` would raise an error if a `NULL` value was entered. 

Alternatively we can loosen the constraint and allow `NULL` for custom preferences.

**Comment by martindsouza** [comment]
Documented and added to change log.
