### ISSUE TITLE
Logger throws exception when quota on tablespace is used

### ISSUE THREAD

**Issue by oluffaroe** [OraOpenSource/Logger#118]
I have installed the logger into a seperate schema and restricted the users quota on the tablespace. But the logger throws an exception when the quota limit is reached. 

This makes it necessary to wrap all calls to logging with exception handling.

In case of exceptions I would instead expect the logging framework to silently ignore the logging instruction.

**Comment by martindsouza** [comment]
I understand your situation. I don't think we'll make any changes to silently ignore logging errors. If an error does occur (i.e. tablespace issue) you should know about it. Most people would want to know when their logging isn't working.

I think this is more of a question on the management of the tablespace, rather than Logger. I don't think you should be wrapping all your calls to Logger with exception handling as it will ruin the entire point of Logger: to make it easy for developers to use. Alternatively here are some ideas I'd recommend:

- Change the `PURGE_AFTER_DAYS` setting in the `LOGGER_PREFS` table. By default it auto deletes debug logs older than 7 days. Perhaps you need to set that to a shorter time frame. You can also modify `PURGE_MIN_LEVEL` which will increase the scope of what is deleted. See https://github.com/OraOpenSource/Logger/blob/master/docs/Installation.md#maintenance for more info.
- Create your own scheduled job that monitors the size of your separate schema. If it's getting too big, start purging records.
- Reduce the current logging level so that only critical items are logger. This is what most people do in production environments: https://github.com/OraOpenSource/Logger/blob/master/docs/Logger%20API.md#set_level  If the tablespace issue is happening on a development environment I suggest expanding the tablespace size.
