### ISSUE TITLE
Better handling of APEX dependencies

### ISSUE THREAD

**Issue by hkpatv** [OraOpenSource/Logger#190]
We had some disruption to components that use logger when we uninstalled APEX schema, even though we weren't using logger for logging any APEX operations, or aware of any dependencies.  Personally I don't think such disruption is acceptable, and think these dependencies should be re-worked.
My suggestion would be to move such apex components into separate package, so that even if this package body were to become invalid during apex removal/upgrade, it wouldn't affect unrelated components, although I understand there may be reluctance to create additional packages.

**Comment by jeffreykemp** [comment]
Thanks hkpatv, good to know about this behaviour.

It is documented in the installation procedure that it automatically detects Apex and installs those dependencies. I think it's reasonable for Logger to assume that most people who have Apex installed are not intending on uninstalling it any time soon, and will 99% of the time expect Logger to have the Apex dependencies pre-installed without having to do anything special.

Also, it's reasonable to expect that uninstalling something as major as Apex in an environment carries a risk of tripping up on some dependencies - this should be done first in a non-Prod environment so that this sort of thing is picked up early and handled.

Perhaps there needs to be some installation options/scrips added, that:

1) stop Logger from installing the Apex dependencies automatically
2) re-install Logger without losing existing logs and preferences (e.g. so that hkpatv can re-install Logger so that it can pick up that Apex is no longer installed)

I think the default installation scripts should still install the full feature set where possible.

**Comment by martindsouza** [comment]
@hkpatv As @jeffreykemp mentioned Logger detects if APEX exists. You could just re-install Logger or try running the following procedure: `exec logger_configure;`

Let us know if it works.

**Comment by hkpatv** [comment]
We just removed the dependency by recompiling before uninstalling apex.  Personally I think the apex stuff used by only a small proportion of users, and the dependencies as is risk  unexpected disruption for the majority, but your decision

**Comment by martindsouza** [comment]
@hkpatv I appreciate your feedback. Based on personal experience the APEX features are used where appropriate. As @jeffreykemp your situation may be a bit of an edge case in that most people don't uninstall APEX after having it installed. 

I'm glad that recompiling logger resolved the issue. Will close the ticket.
